version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_test
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: tester
      MONGO_INITDB_ROOT_PASSWORD: tester$
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
