---
- name: Configure Remote Server
  hosts: web
  become: yes
  vars:
    github_actions_public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"  # Path to your GitHub Actions public key
    ansible_user_public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"    # Path to your local public key for Ansible

  tasks:
    - name: Install prerequisites
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: true

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker's GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository to APT sources
      ansible.builtin.shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo \"${UBUNTU_CODENAME:-$VERSION_CODENAME}\") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        executable: /bin/bash

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Update apt and install docker-ce
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true

    - name: Ensure Docker service is running and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure SSH service is running and enabled
      service:
        name: ssh
        state: started
        enabled: yes

    - name: Ensure SSH access is allowed from GitHub Actions
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^AllowUsers"
        line: "AllowUsers {{ ansible_user }} github-actions"
        state: present
      notify: Restart SSH

    - name: Add GitHub Actions public key to authorized_keys
      authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ github_actions_public_key }}"
        state: present

    - name: Add Ansible public key to authorized_keys
      authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ ansible_user_public_key }}"
        state: present

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted
