name: GPacAPI FastAPI CI/CD
'on':
  push:
    branches:
      - master
      - develop
      - feature/*
      - fix/*
      - hotfix/*
      - refactor/*
      - test/*
      - ci/*
jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pipx
          pipx install poetry
          poetry install
      - name: Run pylint
        run: poetry run pylint src/
      - name: Run black check
        run: poetry run black . --check --diff -v
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pipx
          pipx install poetry
          poetry install
      - name: run build
        run: poetry build
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pipx
          pipx install poetry
          poetry install
      - name: Set up MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: '7.0'
          mongodb-root-username: tester
          mongodb-root-password: tester$
          mongodb-port: 42069
      - name: Wait for MongoDB
        run: |
          until mongo --eval "print('MongoDB is ready')" &>/dev/null; do
            echo "Waiting for MongoDB...";
            sleep 5;
          done
      - name: Run Tests
        run: poetry run pytest --cov=src tests/
